### PR TITLE
Add enzyme testing

### PR DESCRIPTION
**Pull request by mradenovic**
I'm learning to write tests. This PR is more for conversation purpose.

### CODE REVIEW

**Comment by jhowardjr** [comment]
👍looks cleaner than having to mock the external classes. Is it automatically mocking those dependencies or is doing more of a functional test where it’s rendering as it would through a browser?

**Comment by mradenovic** [comment]
[`enzyme`](http://airbnb.io/enzyme/) has `shallow`, `mount` and `render` wrappers. Only `mount` renders in DOM. I think `mount` is good for functional testing.

**Comment by jhowardjr** [comment]
👍 I added the coverage task to display what needs to be tested.

**Comment by jhowardjr** [comment]
@mradenovic I know you said this was for conversation, but do you want to merge this? We can increase the coverage as we go.

**Comment by mradenovic** [comment]
Sure, let me resolve conflicts.

**Comment by mradenovic** [comment]
@jhowardjr I think this is ready.

**Pull request merged**
