### PR TITLE
Mockup

### PR DESCRIPTION
**Pull request by amr08**
@jhowardjr Well I was going to do a little bit more, but ran out of ideas and decided it would be good to put it out there so we can figure out next steps.  Maybe you can try bringing in your variadic npm package and test out how that might work in the app.

Depending on how all that goes, if we have to go a few component levels deep I can toss Redux on there to create some ease, otherwise probably not necessary.  Let me know if you have any ideas you'd like to implement!

### CODE REVIEW

**Comment by amr08** [comment]
@jhowardjr thinking I should send this over to "develop" and then if all looks good, one of us can run the build to merge to master.

**Comment by jhowardjr** [comment]
It looks good to me! Is each card going to be a function?

**Comment by amr08** [comment]
That's just what came to mind initially and then maybe reveal the code behind it all after it runs (all depends on how the package works, I haven't checked it out thoroughly), but i'm totally open to other options!  Another idea could be a dropdown that people select the demos from.

**Comment by jhowardjr** [comment]
I like the idea of code on one side of the card and something to test the function on the other side.

**Comment by jhowardjr** [comment]
@amr08 did you want to push this to master?

**Comment by amr08** [comment]
@jhowardjr I did run the build, but I got side tracked with work stuff last night.  If you get to it before I do feel free to move it over, otherwise, I'll try to set aside some time tonight!

**Pull request merged**
