### PR TITLE
React github user page integration

### PR DESCRIPTION
**Pull request by jhowardjr**
@amr08 I found some configurations that seem to allow react applications to work with github user's pages. Here's the page https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#github-pages. It looks like it works. because your updates are currently live https://variadicjs.github.io/. Let me know if it functions as advertised for you.

### CODE REVIEW

**Comment by amr08** [comment]
@jhowardjr Oh wow that's embarrassing - I didn't realize it would go live as I'm still playing around locally.  (I tend to push up to my branches pretty frequently as I develop).  I was going to add some functionality and after that run the mockup by you and then do a real PR.  But now that it's up, does this look like a good direction to head in as far as UI?

**Comment by jhowardjr** [comment]
Sorry. I can revert it back to the sample theme I was just curious to see how React works with GitHub pages. The direction you are going looks great! Using material-ui is a great idea!

**Comment by jhowardjr** [comment]
@amr08 Promise, no more tinkering on my side. Thanks for the progress you have made!

**Comment by amr08** [comment]
@jhowardjr haha ok great, that's all I was worried about! :)  I'll keep going with this to add some basic functionality, then i'll get a PR over to master so you and others can start playing around with the UI too.

**Pull request merged**
